org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

## Environment Properties
minecraft_version=26.1.2
minecraft_version_short=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.77
loader_version_range=[1,)

## Mod Properties
mod_id=growthcraft_deco
mod_archive_base=growthcraft-deco
mod_name=Growthcraft Decorations
mod_license=GNU General Public License v3.0
mod_version=26.1.2.1
mod_group_id=growthcraft
mod_authors=Alatyami
mod_description=Growthcraft Decorations adds additional decorative versions of vanilla blocks for Minecraft.

# Development runtime mods
jei_version=29.6.2.33
